import test from 'node:test';
import assert from 'node:assert/strict';
import { foldModelTraceEvents, modelStageMetrics } from '../lib/types/observation/model-trace.js';
const start={type:'step/start',seq:1,time:100,data:{turn:1,step:1}};
const message={type:'assistant/message',seq:6,time:1000,data:{turn:1,step:1,message:{content:[{type:'reasoning',text:'abc'}]}}};
const parts=[200,250,300].map((time,i)=>({type:'assistant/live-chunk',seq:2+i,time,data:{turn:1,step:1,chunk:{type:'reasoning-delta',index:0,text:'abc'[i]}}}));
const packed={type:'chunkrow/reasoning-chunks',seq:2,time:200,data:{turn:1,step:1,index:0,texts:['a','b','c'],dt:[50,50]}};
const attempt={type:'assistant/attempt',seq:2,time:200,data:{turn:1,step:1,stream:[{type:'reasoning-chunks',time0:200,index:0,dt:[50,50],texts:['a','b','c']}]}};
test('RC1 packed history has identical reasoning fragments and timing to live stream',()=>{const a=foldModelTraceEvents([start,...parts,message]).get('1:1');const b=foldModelTraceEvents([start,packed,message]).get('1:1');assert.deepEqual(a,b);assert.deepEqual(modelStageMetrics(a,2000),modelStageMetrics(b,2000));});
test('assistant/attempt.stream matches packed reasoning fragments and timing',()=>{const a=foldModelTraceEvents([start,attempt,message]).get('1:1');const b=foldModelTraceEvents([start,packed,message]).get('1:1');assert.deepEqual(a,b);assert.deepEqual(modelStageMetrics(a,2000),modelStageMetrics(b,2000));});
test('silent running stream does not accumulate reasoning time',()=>{const a=foldModelTraceEvents([start,...parts]).get('1:1');assert.equal(modelStageMetrics(a,999999).visibleReasoningMs,100);});
test('malformed packed timing is not guessed',()=>{const a=foldModelTraceEvents([start,{...packed,data:{...packed.data,dt:[50]}}]).get('1:1');assert.equal(a.attempts[0].fragments.length,0);});
